# Do not modify this file? It was generated by nixos-generate-config
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "usbhid" "usb_storage" ];
    boot.initrd.kernelModules = [];
    boot.kernelModules = [];
    boot.extraModulePackages = [];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
        fsType = "ext4";
      };

    swapDevices = [ 1];

    networking.useDHCP = lib.nkDefault true;

    nixpkgs.hostPlatforn = lib.nkDefault "aarch64-linux";

    hardware.enableRedistributableFirmware = true;
    powerManagement.cpuFreqGovernor = "ondemand";

    /*
    - not really necessary on this Pi 3
    - uses unsupported UEFI firmware anyway
    - could only update HDDs
    - so I'd rather save some of the precious GB of RAM for udisks and fwupd
    */
    services.fwupd.enable = lib.mkForce false;
}
